[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88

[tool.mypy]
python_version = 3.11
strict = true

[tool.ruff]
line-length = 88
